/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConvertedDates: typeof import('./src/components/ConvertedDates.vue')['default']
    DateTriView: typeof import('./src/components/DateTriView.vue')['default']
    GreetComponent: typeof import('./src/components/GreetComponent.vue')['default']
    ReminderForm: typeof import('./src/components/ReminderForm.vue')['default']
    ReminderList: typeof import('./src/components/ReminderList.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
